"""Outbound repository ports (Gate 04, extended Gate 08).

Repository contracts express DOMAIN/APPLICATION needs, never SQL. They are
derived from the actual Gate 03 domain entities and from the use cases that
Gate 04 orchestrates. Missing aggregates raise ``EntityNotFound``.

Only repositories justified by a current use case are declared. Caregiver
relationships and identity mappings are declared here for the Gate 08
relational identity and clinical authorization contracts; document references
remain intentionally undeclared — no use case requires them.
"""

from datetime import datetime
from typing import Protocol, runtime_checkable
from uuid import UUID

from ...domain.entities import (
    AIReviewArtifact,
    CareTask,
    CareTaskStatus,
    CareTeamMember,
    CaregiverRelationship,
    DocumentKind,
    DocumentReference,
    Facility,
    GlucoseObservation,
    IdentityPatientMapping,
    MealObservation,
    MedicationPlan,
    Notification,
    NotificationStatus,
    Patient,
)
from ...domain.entities.ai_artifact import ReviewState


@runtime_checkable
class FacilityRepository(Protocol):
    def add(self, facility: Facility) -> None: ...
    def get(self, facility_id: UUID) -> Facility: ...
    def list(self) -> list[Facility]: ...
    def save(self, facility: Facility) -> None: ...


@runtime_checkable
class PatientRepository(Protocol):
    def add(self, patient: Patient) -> None: ...
    def get(self, patient_id: UUID) -> Patient: ...
    def save(self, patient: Patient) -> None: ...
    def list(self) -> list[Patient]: ...


@runtime_checkable
class CareTeamMemberRepository(Protocol):
    def add(self, member: CareTeamMember) -> None: ...
    def get(self, user_id: UUID) -> CareTeamMember: ...
    def get_by_id(self, member_id: UUID) -> CareTeamMember: ...
    def list(self) -> list[CareTeamMember]: ...
    def save(self, member: CareTeamMember) -> None: ...


@runtime_checkable
class GlucoseObservationRepository(Protocol):
    def add(self, observation: GlucoseObservation) -> None: ...
    def get(self, observation_id: UUID) -> GlucoseObservation: ...
    def list_for_patient(self, patient_id: UUID) -> list[GlucoseObservation]: ...


@runtime_checkable
class MealObservationRepository(Protocol):
    def add(self, observation: MealObservation) -> None: ...
    def get(self, observation_id: UUID) -> MealObservation: ...
    def save(self, observation: MealObservation) -> None: ...
    def list_for_patient(self, patient_id: UUID) -> list[MealObservation]: ...


@runtime_checkable
class MedicationPlanRepository(Protocol):
    def add(self, plan: MedicationPlan) -> None: ...
    def get(self, plan_id: UUID) -> MedicationPlan: ...
    def list(self) -> list[MedicationPlan]: ...
    def list_for_patient(self, patient_id: UUID) -> list[MedicationPlan]: ...


@runtime_checkable
class CareTaskRepository(Protocol):
    def add(self, task: CareTask) -> None: ...
    def get(self, task_id: UUID) -> CareTask: ...
    def save(self, task: CareTask) -> None: ...
    def list_for_patient(self, patient_id: UUID, status: CareTaskStatus | None = None) -> list[CareTask]: ...
    def list_for_assignee(self, assigned_to_user_id: UUID, status: CareTaskStatus | None = None) -> list[CareTask]: ...
    def list_for_facility(self, facility_id: UUID, status: CareTaskStatus | None = None) -> list[CareTask]: ...


@runtime_checkable
class AIReviewArtifactRepository(Protocol):
    def add(self, artifact: AIReviewArtifact) -> None: ...
    def get(self, artifact_id: UUID) -> AIReviewArtifact: ...
    def list_by_state(self, state: ReviewState) -> list[AIReviewArtifact]: ...
    def list_for_patient(self, patient_id: UUID) -> list[AIReviewArtifact]: ...


@runtime_checkable
class CaregiverRelationshipRepository(Protocol):
    def add(self, relationship: CaregiverRelationship) -> None: ...
    def get(self, relationship_id: UUID) -> CaregiverRelationship: ...
    def save(self, relationship: CaregiverRelationship) -> None: ...
    def list_for_caregiver(self, caregiver_user_id: UUID) -> list[CaregiverRelationship]: ...
    def list_for_patient(self, patient_id: UUID) -> list[CaregiverRelationship]: ...
    def find_by_pair(
        self, caregiver_user_id: UUID, patient_id: UUID
    ) -> CaregiverRelationship | None: ...
    def get_verified_for_patient(
        self, caregiver_user_id: UUID, patient_id: UUID
    ) -> CaregiverRelationship | None: ...


@runtime_checkable
class IdentityPatientMappingRepository(Protocol):
    def add(self, mapping: IdentityPatientMapping) -> None: ...
    def save(self, mapping: IdentityPatientMapping) -> None: ...
    def get(self, mapping_id: UUID) -> IdentityPatientMapping: ...
    def get_by_user_id(self, user_id: UUID) -> IdentityPatientMapping | None: ...
    def get_by_patient_id(self, patient_id: UUID) -> IdentityPatientMapping | None: ...
    def list(self) -> list[IdentityPatientMapping]: ...


@runtime_checkable
class NotificationRepository(Protocol):
    def add(self, notification: Notification) -> None: ...
    def get(self, notification_id: UUID) -> Notification: ...
    def save(self, notification: Notification) -> None: ...
    def list_for_recipient(self, recipient_id: UUID, limit: int = 50, offset: int = 0) -> list[Notification]: ...
    def list_for_patient(self, patient_id: UUID, limit: int = 50, offset: int = 0) -> list[Notification]: ...
    def list_due(self, before: datetime, limit: int = 50) -> list[Notification]: ...
    def list_for_tenant(self, status: NotificationStatus | None = None, limit: int = 50, offset: int = 0) -> list[Notification]: ...
    def count_for_tenant(self, status: NotificationStatus | None = None) -> int: ...


@runtime_checkable
class DocumentReferenceRepository(Protocol):
    def add(self, doc_ref: DocumentReference) -> None: ...
    def get(self, document_id: UUID) -> DocumentReference: ...
    def list_for_patient(self, patient_id: UUID, kind: DocumentKind | None = None) -> list[DocumentReference]: ...
    def list_for_tenant(self, limit: int = 50, offset: int = 0) -> list[DocumentReference]: ...
    def delete(self, document_id: UUID) -> None: ...