"""Outbound repository ports (Gate 04, extended Gate 08).

Repository contracts express DOMAIN/APPLICATION needs, never SQL. They are
derived from the actual Gate 03 domain entities and from the use cases that
Gate 04 orchestrates. Missing aggregates raise ``EntityNotFound``.

Only repositories justified by a current use case are declared. Caregiver
relationships and identity mappings are declared here for the Gate 08
relational identity and clinical authorization contracts; document references
remain intentionally undeclared — no use case requires them.
"""

from typing import Protocol, runtime_checkable
from uuid import UUID

from ...domain.entities import (
    AIReviewArtifact,
    CareTask,
    CareTeamMember,
    CaregiverRelationship,
    GlucoseObservation,
    IdentityPatientMapping,
    MealObservation,
    MedicationPlan,
    Patient,
)
from ...domain.entities.ai_artifact import ReviewState


@runtime_checkable
class PatientRepository(Protocol):
    def add(self, patient: Patient) -> None: ...
    def get(self, patient_id: UUID) -> Patient: ...
    def save(self, patient: Patient) -> None: ...
    def list(self) -> list[Patient]: ...


@runtime_checkable
class CareTeamMemberRepository(Protocol):
    def add(self, member: CareTeamMember) -> None: ...
    def get(self, user_id: UUID) -> CareTeamMember: ...
    def list(self) -> list[CareTeamMember]: ...


@runtime_checkable
class GlucoseObservationRepository(Protocol):
    def add(self, observation: GlucoseObservation) -> None: ...
    def get(self, observation_id: UUID) -> GlucoseObservation: ...
    def list_for_patient(self, patient_id: UUID) -> list[GlucoseObservation]: ...


@runtime_checkable
class MealObservationRepository(Protocol):
    def add(self, observation: MealObservation) -> None: ...
    def get(self, observation_id: UUID) -> MealObservation: ...
    def save(self, observation: MealObservation) -> None: ...
    def list_for_patient(self, patient_id: UUID) -> list[MealObservation]: ...


@runtime_checkable
class MedicationPlanRepository(Protocol):
    def add(self, plan: MedicationPlan) -> None: ...
    def get(self, plan_id: UUID) -> MedicationPlan: ...
    def list(self) -> list[MedicationPlan]: ...
    def list_for_patient(self, patient_id: UUID) -> list[MedicationPlan]: ...


@runtime_checkable
class CareTaskRepository(Protocol):
    def add(self, task: CareTask) -> None: ...
    def get(self, task_id: UUID) -> CareTask: ...
    def save(self, task: CareTask) -> None: ...
    def list_for_patient(self, patient_id: UUID) -> list[CareTask]: ...


@runtime_checkable
class AIReviewArtifactRepository(Protocol):
    def add(self, artifact: AIReviewArtifact) -> None: ...
    def get(self, artifact_id: UUID) -> AIReviewArtifact: ...
    def list_by_state(self, state: ReviewState) -> list[AIReviewArtifact]: ...
    def list_for_patient(self, patient_id: UUID) -> list[AIReviewArtifact]: ...


@runtime_checkable
class CaregiverRelationshipRepository(Protocol):
    def add(self, relationship: CaregiverRelationship) -> None: ...
    def get(self, relationship_id: UUID) -> CaregiverRelationship: ...
    def save(self, relationship: CaregiverRelationship) -> None: ...
    def list_for_caregiver(self, caregiver_user_id: UUID) -> list[CaregiverRelationship]: ...
    def list_for_patient(self, patient_id: UUID) -> list[CaregiverRelationship]: ...
    def find_by_pair(
        self, caregiver_user_id: UUID, patient_id: UUID
    ) -> CaregiverRelationship | None: ...
    def get_verified_for_patient(
        self, caregiver_user_id: UUID, patient_id: UUID
    ) -> CaregiverRelationship | None: ...


@runtime_checkable
class IdentityPatientMappingRepository(Protocol):
    def add(self, mapping: IdentityPatientMapping) -> None: ...
    def save(self, mapping: IdentityPatientMapping) -> None: ...
    def get(self, mapping_id: UUID) -> IdentityPatientMapping: ...
    def get_by_user_id(self, user_id: UUID) -> IdentityPatientMapping | None: ...
    def get_by_patient_id(self, patient_id: UUID) -> IdentityPatientMapping | None: ...
    def list(self) -> list[IdentityPatientMapping]: ...