#!/usr/bin/env python3
"""Generate RSA-2048 key pair for development JWT signing and write .env.

Usage:
    python -m scripts.generate_dev_keys

Writes:
    config/dev_keys/dev_private.pem
    config/dev_keys/dev_public.pem
    .env  (overwrites if exists — safe for dev)
"""
from __future__ import annotations

import os
import sys
import textwrap

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa


def generate() -> None:
    os.makedirs("config/dev_keys", exist_ok=True)

    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)

    private_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode()

    public_pem = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode()

    with open("config/dev_keys/dev_private.pem", "w") as f:
        f.write(private_pem)
    with open("config/dev_keys/dev_public.pem", "w") as f:
        f.write(public_pem)

    print("Keys written to config/dev_keys/")

    # Write .env with PEM content inline (newlines escaped for env-var format)
    private_escaped = private_pem.replace("\n", "\\n")
    public_escaped = public_pem.replace("\n", "\\n")

    env_content = textwrap.dedent(f"""\
        # THALI x P.L.A.T.E. — Development environment
        # Generated by scripts/generate_dev_keys.py
        # DO NOT COMMIT THIS FILE

        THALI_APP__ENV=development
        THALI_DATABASE__URL=postgresql+psycopg://thali_user:thali_rehearsal_password@localhost:5432/thali_db
        THALI_REDIS__ENABLED=false
        THALI_STORAGE__ENDPOINT_URL=http://localhost:9000
        THALI_STORAGE__BUCKET=thali-documents
        THALI_STORAGE__REGION=ap-south-1
        THALI_STORAGE__ACCESS_KEY_ID=thali_minio_dev
        THALI_STORAGE__SECRET_ACCESS_KEY=thali_minio_secret_dev
        THALI_AUTH__ACCESS_TOKEN_EXPIRE_MINUTES=60
        THALI_AUTH__REFRESH_TOKEN_EXPIRE_DAYS=7
        THALI_AUTH__PRIVATE_KEY_PEM={private_escaped}
        THALI_AUTH__PUBLIC_KEY_PEM={public_escaped}
        THALI_WHATSAPP__VERIFY_TOKEN=thali-verify-dev
        THALI_AI__PROVIDER=deterministic
        THALI_OBSERVABILITY__LOG_LEVEL=INFO
        THALI_SECURITY__ALLOWED_ORIGINS=["http://localhost:3000","http://localhost:8000"]
        THALI_SEED_ENABLED=true
        THALI_SEED_ADMIN_PASSWORD=admin-change-me-2026
    """)

    with open(".env", "w") as f:
        f.write(env_content)

    print(".env written.")
    print()
    print("Quick-start:")
    print("  docker-compose up")
    print("  # or locally:")
    print("  alembic upgrade head && python -m scripts.seed_dev_stack")
    print("  uvicorn backend.interfaces.http.app:create_app --factory --host 0.0.0.0 --port 8000")


if __name__ == "__main__":
    generate()
