import React from "react";
import {
  Linking,
  Modal,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, radii, spacing, touchTarget, typography } from "../../../theming/tokens";
import { PatientDocumentCard } from "./PatientDocumentCard";
import { usePatientDocuments } from "../api";
import type { PatientDocument } from "../types";

export type DocumentViewerModalProps = {
  visible: boolean;
  onClose: () => void;
  patientId: string | null;
};

export function DocumentViewerModal({
  visible,
  onClose,
  patientId,
}: DocumentViewerModalProps) {
  const { data: documents = [] } = usePatientDocuments(patientId);

  const handleOpenDocument = (doc: PatientDocument) => {
    if (doc.download_url) {
      void Linking.openURL(doc.download_url);
    }
  };

  return (
    <Modal
      visible={visible}
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={onClose}
    >
      <SafeAreaView style={styles.container}>
        <View style={styles.header}>
          <View>
            <Text style={styles.title} allowFontScaling>
              Documents & Reports
            </Text>
            <Text style={styles.subtitle} allowFontScaling>
              Verified clinical reports and summaries
            </Text>
          </View>
          <TouchableOpacity
            style={styles.closeButton}
            onPress={onClose}
            accessibilityRole="button"
            accessibilityLabel="Close documents modal"
          >
            <Text style={styles.closeText} allowFontScaling>
              ✕
            </Text>
          </TouchableOpacity>
        </View>

        <ScrollView contentContainerStyle={styles.content}>
          <View style={styles.securityBox} accessibilityRole="summary">
            <Text style={styles.securityTitle} allowFontScaling>
              Secure Medical Records
            </Text>
            <Text style={styles.securityText} allowFontScaling>
              Documents are encrypted and authorized via time-limited secure links. No clinical documents are publicly exposed.
            </Text>
          </View>

          {documents.length === 0 ? (
            <View style={styles.emptyContainer}>
              <Text style={styles.emptyIcon} allowFontScaling>
                📄
              </Text>
              <Text style={styles.emptyTitle} allowFontScaling>
                No documents available yet
              </Text>
              <Text style={styles.emptySubtitle} allowFontScaling>
                Clinical summaries and consultation letters generated by your doctor will appear here.
              </Text>
            </View>
          ) : (
            documents.map((doc) => (
              <PatientDocumentCard
                key={doc.id}
                document={doc}
                onView={handleOpenDocument}
              />
            ))
          )}
        </ScrollView>
      </SafeAreaView>
    </Modal>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  title: {
    fontSize: typography.fontSize.title,
    fontWeight: typography.weight.bold,
    color: colors.textPrimary,
  },
  subtitle: {
    fontSize: typography.fontSize.caption,
    color: colors.textSecondary,
  },
  closeButton: {
    minWidth: touchTarget.min,
    minHeight: touchTarget.min,
    alignItems: "center",
    justifyContent: "center",
  },
  closeText: {
    fontSize: 18,
    color: colors.textSecondary,
    fontWeight: "bold",
  },
  content: {
    padding: spacing.md,
  },
  securityBox: {
    backgroundColor: "#F0F7F9",
    borderRadius: radii.md,
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  securityTitle: {
    fontSize: typography.fontSize.caption,
    fontWeight: typography.weight.bold,
    color: colors.primary,
    marginBottom: 2,
  },
  securityText: {
    fontSize: typography.fontSize.caption,
    color: colors.textSecondary,
    lineHeight: 18,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: spacing.xxl,
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: spacing.md,
  },
  emptyTitle: {
    fontSize: typography.fontSize.headline,
    fontWeight: typography.weight.bold,
    color: colors.textPrimary,
  },
  emptySubtitle: {
    fontSize: typography.fontSize.bodySmall,
    color: colors.textSecondary,
    marginTop: spacing.xs,
    textAlign: "center",
    maxWidth: 280,
  },
});
